Merge pipelines

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -14,7 +14,6 @@ env:
 
 jobs:
   build-ubuntu:
-    runs-on: ubuntu-latest
     strategy:
       matrix:
         build-type: ["Debug", "Release"]
@@ -23,6 +22,7 @@ jobs:
           { c: "clang-14", cxx: "clang++-14", package: "clang-14" }
         ]
     name: Build & Test ${{ matrix.build-type }} with ${{ matrix.compiler.cxx }}
+    runs-on: ubuntu-latest
     timeout-minutes: 30
     steps:
       - name: Checkout code
@@ -46,3 +46,58 @@ jobs:
 
       - name: Test
         run: cd ${{ env.BUILD_DIRECTORY }} && ctest -j8 -T test --no-compress-output
+
+  clang-format-check:
+    name: Clang-format Check
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    needs: [build-ubuntu]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          submodules: true
+
+      - name: Install dependencies
+        run: |
+          sudo apt-get update && \
+          sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }} clang-14
+
+      - name: Check clang-format
+        run: |
+          FILES=$(find . -not -path "./third_party/*" -not -path "./build/*" \( -name '*.cc' -o -name '*.c' -o -name '*.h' \))
+          TMPFILE="./formatted_file"
+          for file in $FILES; do
+            clang-format -style=file $file > $TMPFILE
+            if ! diff $file $TMPFILE > /dev/null; then
+              echo "Clang-format failed on $file"
+              rm $TMPFILE
+              exit 1
+            fi 
+            rm $TMPFILE
+          done
+          echo "Clang-format check successful"
+
+  doxygen-check:
+    name: Doxygen Check
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    needs: [build-ubuntu]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          submodules: recursive
+
+      - name: Install dependencies
+        run: sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }} clang-14 doxygen graphviz
+
+      - name: Check doxygen
+        env:
+          CC: clang
+          CXX: clang++
+        run: |
+          cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Debug -DDOXYGEN_BUILD_ENABLED=ON
+          cmake --build ${{ env.BUILD_DIRECTORY }} --target doxygen -- --no-print-directory
