disable other builds

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -13,68 +13,68 @@ env:
   BUILD_DIRECTORY: build
 
 jobs:
-  build-ubuntu:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        build-type: [DEBUG, RELEASE]
-    name: Build & Test <${{ matrix.build-type }}>
-    timeout-minutes: 30
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-          submodules: true
+  # build-ubuntu:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       build-type: [DEBUG, RELEASE]
+  #   name: Build & Test <${{ matrix.build-type }}>
+  #   timeout-minutes: 30
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.sha }}
+  #         submodules: true
 
-      - name: Install dependencies
-        run: sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }}
+  #     - name: Install dependencies
+  #       run: sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }}
 
-      - name: Build
-        run: |
-          if [ "${{matrix.build-type}}" == "DEBUG" ]; then
-            cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Debug && cmake --build ${{ env.BUILD_DIRECTORY }} -j10
-          else
-            cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Release && cmake --build ${{ env.BUILD_DIRECTORY }} -j10
-          fi
+  #     - name: Build
+  #       run: |
+  #         if [ "${{matrix.build-type}}" == "DEBUG" ]; then
+  #           cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Debug && cmake --build ${{ env.BUILD_DIRECTORY }} -j10
+  #         else
+  #           cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Release && cmake --build ${{ env.BUILD_DIRECTORY }} -j10
+  #         fi
 
-      - name: Test
-        run: cd ${{ env.BUILD_DIRECTORY }} && ctest -j8 -T test --no-compress-output
+  #     - name: Test
+  #       run: cd ${{ env.BUILD_DIRECTORY }} && ctest -j8 -T test --no-compress-output
 
-  extra-checks:
-    runs-on: ubuntu-latest
-    needs: [build-ubuntu]
-    name: Extra Checks
-    timeout-minutes: 10
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-          submodules: true
+  # extra-checks:
+  #   runs-on: ubuntu-latest
+  #   needs: [build-ubuntu]
+  #   name: Extra Checks
+  #   timeout-minutes: 10
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.sha }}
+  #         submodules: true
 
-      - name: Install dependencies
-        run: sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }} doxygen graphviz clang-format 
+  #     - name: Install dependencies
+  #       run: sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }} doxygen graphviz clang-format 
 
-      - name: Check clang-format
-        run: |
-          FILES=$(find . -not -path "./third_party/*" -not -path "./build/*" \( -name '*.cc' -o -name '*.c' -o -name '*.h' \))
-          TMPFILE="./formatted_file"
-          for file in $FILES; do
-            clang-format -style=file $file > $TMPFILE
-            if ! diff $file $TMPFILE > /dev/null; then
-              echo "Clang-format failed on $file"
-              rm $TMPFILE
-              exit 1
-            fi 
-            rm $TMPFILE
-          done
-          echo "Clang-format check successful"
+  #     - name: Check clang-format
+  #       run: |
+  #         FILES=$(find . -not -path "./third_party/*" -not -path "./build/*" \( -name '*.cc' -o -name '*.c' -o -name '*.h' \))
+  #         TMPFILE="./formatted_file"
+  #         for file in $FILES; do
+  #           clang-format -style=file $file > $TMPFILE
+  #           if ! diff $file $TMPFILE > /dev/null; then
+  #             echo "Clang-format failed on $file"
+  #             rm $TMPFILE
+  #             exit 1
+  #           fi 
+  #           rm $TMPFILE
+  #         done
+  #         echo "Clang-format check successful"
 
-      - name: Check doxygen
-        run: |
-          cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Debug -DDOXYGEN_BUILD_ENABLED=ON
-          cmake --build ${{ env.BUILD_DIRECTORY }} --target doxygen -- --no-print-directory
+  #     - name: Check doxygen
+  #       run: |
+  #         cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Debug -DDOXYGEN_BUILD_ENABLED=ON
+  #         cmake --build ${{ env.BUILD_DIRECTORY }} --target doxygen -- --no-print-directory
 
   sonar-cloud:
     name: Build and analyze
