Add clang format check pipeline (#19)
* Add clang-format pipeline
* Use general env variable in cicd pipelines 
* Move doxygen check from build pipeline to the extra check

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -8,33 +8,71 @@ on:
     branches:
       - '*'
 
+env:
+  BUILD_DEPENDENCIES: g++ cmake build-essential checkinstall zlib1g-dev libssl-dev
+  BUILD_DIRECTORY: build
+
 jobs:
-  build-linux:
+  build-ubuntu:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        build-type: [debug, release]
-    name: Build and Test ${{ matrix.build-type }}
+        build-type: [DEBUG, RELEASE]
+    name: Build & Test <${{ matrix.build-type }}>
+    timeout-minutes: 30
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.sha }}
           submodules: true
 
       - name: Install dependencies
-        run: sudo apt-get install -y g++ cmake build-essential checkinstall zlib1g-dev libssl-dev doxygen graphviz
+        run: sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }}
 
       - name: Build
         run: |
-          if [ "${{matrix.build-type}}" == "debug" ]; then
-            cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build -j10
+          if [ "${{matrix.build-type}}" == "DEBUG" ]; then
+            cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Debug && cmake --build ${{ env.BUILD_DIRECTORY }} -j10
           else
-            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j10
+            cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Release && cmake --build ${{ env.BUILD_DIRECTORY }} -j10
           fi
 
       - name: Test
-        run: cd build && ctest -j8 -T test --no-compress-output
+        run: cd ${{ env.BUILD_DIRECTORY }} && ctest -j8 -T test --no-compress-output
 
-      - name: doxygen
-        run: cmake --build build --target doxygen -- --no-print-directory
+  extra-checks:
+    runs-on: ubuntu-latest
+    needs: [build-ubuntu]
+    name: Extra Checks
+    timeout-minutes: 10
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          submodules: true
+
+      - name: Install dependencies
+        run: sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }} doxygen graphviz clang-format 
+
+      - name: Build
+        run:  cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Debug && cmake --build ${{ env.BUILD_DIRECTORY }} -j10
+
+      - name: Check clang-format
+        run: |
+          FILES=$(find . -not -path "./third_party/*" -not -path "./build/*" \( -name '*.cc' -o -name '*.c' -o -name '*.h' \))
+          TMPFILE="./formatted_file"
+          for file in $FILES; do
+            clang-format -style=file $file > $TMPFILE
+            if ! diff $file $TMPFILE > /dev/null; then
+              echo "Clang-format failed on $file"
+              rm $TMPFILE
+              exit 1
+            fi 
+            rm $TMPFILE
+          done
+          echo "Clang-format check successful"
+
+      - name: Check doxygen
+        run: cmake --build ${{ env.BUILD_DIRECTORY }} --target doxygen -- --no-print-directory
