Add clang-format pipeline

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -13,11 +13,11 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        build-type: [debug, release]
-    name: Build and Test ${{ matrix.build-type }}
+        build-type: [DEBUG, RELEASE]
+    name: Build & Test <${{ matrix.build-type }}>
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
           ref: ${{ github.event.pull_request.head.sha }}
           submodules: true
@@ -27,7 +27,7 @@ jobs:
 
       - name: Build
         run: |
-          if [ "${{matrix.build-type}}" == "debug" ]; then
+          if [ "${{matrix.build-type}}" == "DEBUG" ]; then
             cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build -j10
           else
             cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j10
@@ -38,3 +38,26 @@ jobs:
 
       - name: doxygen
         run: cmake --build build --target doxygen -- --no-print-directory
+
+  clang-format:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          submodules: true
+
+      - name: Install clang-format
+        run: sudo apt-get install -y clang-format 
+
+      - name: Run clang-format
+        run: |
+          FILES=$(find . -name '*.cc' -o -name '*.c' -o -name '*.h')
+          for file in $FILES; do
+            clang-format -style=file $file > formatted_file
+            if ! diff $file formatted_file > /dev/null; then
+              echo "Clang-format failed on $file"
+              exit 1
+            fi
+          done
